vich_uploader:
    db_driver: orm

    # metadata:
    #     type: attribute

    # mappings:
    #     cvs_directory:
    #         uri_prefix: /uploads/cvs
    #         upload_destination: '%kernel.project_dir%/public/uploads/cvs'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
